// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXc31bByorOjdEU9jyrf8oc85T6zPKcG0',
    appId: '1:364308968037:web:4cb873421af8d8ed7d0c8c',
    messagingSenderId: '364308968037',
    projectId: 'chat-app-auth-5a260',
    authDomain: 'chat-app-auth-5a260.firebaseapp.com',
    storageBucket: 'chat-app-auth-5a260.firebasestorage.app',
    measurementId: 'G-EHZ29X5KV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArqcy1JUkdVPLjQ4wfbE3FrgiDH83Gx8E',
    appId: '1:364308968037:android:c7cbd738da49b6ab7d0c8c',
    messagingSenderId: '364308968037',
    projectId: 'chat-app-auth-5a260',
    storageBucket: 'chat-app-auth-5a260.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUG-1hMgctWTLo2xSPC951IoFbo_-zPFM',
    appId: '1:364308968037:ios:b48c167b343159667d0c8c',
    messagingSenderId: '364308968037',
    projectId: 'chat-app-auth-5a260',
    storageBucket: 'chat-app-auth-5a260.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
